export const data = {
  newCar: [
    {
      make: "BMW",
      model: "Lux",
      release_date: 2013,
      transmission_type: "MANUAL",
      size: "Compact",
      style: "Coupe",
      price: 768644,
    },
    {
      make: "BMW1!@#$%^&*",
      model: "LUX~!@#$%^&***",
      release_date: 2017,
      transmission_type: "MANUAL",
      size: "Compact",
      style: "Coupe?????><",
      price: 768644,
    },
    {
      make: "BMW 2",
      model: "LUX",
      release_date: "2019",
      transmission_type: "Autoclick",
      size: "Compact",
      style: "Coupe",
      price: 768644,
    },
    {
      make: "BMW 3",
      model: "LUX",
      release_date: "2019",
      transmission_type: "MANUAL",
      size: "small",
      style: "Coupe",
      price: 768644,
    },
    {
      make: "BMW 4",
      model: "LUX",
      release_date: "999",
      transmission_type: "MANUAL",
      size: "Compact",
      style: "Coupe",
      price: 768644,
    },
    {
      make: "BMW fail",
      model: "LUX",
      release_date: "2100",
      transmission_type: "MANUAL",
      size: "Compact",
      style: "Coupe",
      price: 768644,
    },
    {
      make: "BMW 6",
      model: "LUX",
      release_date: "2015aa",
      transmission_type: "MANUAL",
      size: "Compact",
      style: "Coupe",
      price: 768644,
    },
    {
      make: "BMW fail",
      model: "LUX",
      release_date: "1999.9",
      transmission_type: "MANUAL",
      size: "Compact",
      style: "Coupe",
      price: 768644,
    },
    {
      make: "BMW fail",
      model: "LUX",
      release_date: "2019",
      transmission_type: "MANUAL",
      size: "Compact",
      style: "Coupe",
      price: "89",
    },
    {
      make: "BMW fail",
      model: "LUX",
      release_date: 2013,
      transmission_type: "MANUAL",
      size: "Compact",
      style: "Coupe",
      price: "100000000000000000000000000000092300",
    },
    {
      make: "BMW fail",
      model: "LUX",
      release_date: "2019",
      transmission_type: "MANUAL",
      size: "Compact",
      style: "Coupe",
      price: "03333.5555444",
    },
    {
      make: "BMW 11",
      model: "LUX",
      release_date: "2019",
      transmission_type: "MANUAL",
      size: "Compact",
      style: "Coupe",
      price: "ee",
    },
    {
      model: "LUX 12",
      release_date: 2012,
      transmission_type: "MANUAL",
      size: "Compact",
      style: "Coupe",
      price: 768644,
    },

    {
      make: "BMW 13",
      release_date: 2012,
      transmission_type: "MANUAL",
      size: "Compact",
      style: "Coupe",
      price: 768644,
    },
    {
      make: "BMW 14",
      model: "LUX",
      transmission_type: "MANUAL",
      size: "Compact",
      style: "Coupe",
      price: 768644,
    },
    {
      make: "BMW 15",
      model: "LUX",
      release_date: 2012,
      size: "Compact",
      style: "Coupe",
      price: 768644,
    },
    {
      make: "BMW 16",
      model: "LUX",
      release_date: 2012,
      transmission_type: "MANUAL",
      style: "Coupe",
      price: 768644,
    },
    {
      make: "BMW 17",
      model: "LUX",
      release_date: 2012,
      transmission_type: "MANUAL",
      size: "Compact",
      price: 768644,
    },
    {
      make: "BMW 18",
      model: "LUX",
      release_date: 2012,
      transmission_type: "MANUAL",
      size: "Compact",
      style: "Coupe",
    },
  ],
  createdMessage: "Create Car Successfully!",
};
